
# Types
bug:
    - '/type bug'

cicd:
    - '/type cicd'

documentation:
    - '/type documentation'

test-automation:
    - '/type test-automation'

translation:
    - '/type translation'

task:
    - '/type task'

enhancement:
    - '/type enhancement'