# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"

  commands:
  - python -m pip install -r requirements.txt
  - make
  - mkdir -p _readthedocs/html/
  - cp -r cpython/Doc/build/html/* _readthedocs/html/

python:
  install:
    - requirements: requirements.txt

submodules:
  include: all
