blank_issues_enabled: false
contact_links:
  - name: PyGreece Community Discord Server
    url: https://discord.gg/evcNPRVCMB
    about: To PyGreece είναι μία online κοινότητα προγραμματιστών Python. Ακολουθόντας το link μπορείται να συμμετέχεται και σεις στην online κοινότητα μας στο discord!
