name: Run pre-commit

on:
  push:
    branches:
      - 3.*
      - main
  pull_request:

jobs:
  test:
    name: Run pre-commit.ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: "true"
          fetch-depth: 2
      - name: Setup python
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: "3.x"
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y hunspell hunspell-el gettext language-pack-el locales-all
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - uses: pre-commit-ci/lite-action@9d882e7a565f7008d4faf128f27d1cb6503d4ebf # v1.0.2
        if: always()
